mybatis:
  config-locations : classpath:mybatis/mybatis-config.xml
  mapper-locations : classpath*:com/midea/jr/ecf/channel/front/**/*Mapper.xml
  type-aliases-package : com.midea.jr.ecf.channel.front

spring :
  datasource :
    type  : com.alibaba.druid.pool.DruidDataSource
    url : ?characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    username :
    password :
    driverClassName : com.mysql.jdbc.Driver
    #连接池的配置信息
    initialSize : 5
    minIdle : 5
    maxActive : 20
    maxWait : 60000
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
    filters : stat,wall,log4j
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

zk :
  dubbo :
      ecf :
        address :





    
  